version: '3.4'

services:
  cmscapamedikal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CapaMedikalDB=Server=CODEADD;Database=CapaMedikalDB;User id=capamed; Password=capa1987*;
    ports:
      - "32780:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  cmscapamedikalapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CapaMedikalDB=Server=CODEADD;Database=CapaMedikalDB;User id=capamed; Password=capa1987*;
    ports:
      - "32781:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
